version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Starting pre_build. Install npm dependencies
      - npm install
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Starting build
      - npm run build
  post_build:
    commands:
      - echo Entered post_build nothing to do here
artifacts:
  files:
    - Procfile
    - node_modules
    - build